"""initial schema

Revision ID: 34f62fc91839
Revises:
Create Date: 2026-06-12 09:12:20.101712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34f62fc91839"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "RUNNING",
                "PAUSED",
                "HALTED",
                "UNCONFIGURED",
                name="bot_state_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("halted_reason", sa.Text(), nullable=True),
        sa.Column("hwm_equity", sa.Float(), nullable=True),
        sa.Column("day_start_equity", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("id = 1", name="ck_bot_state_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("o", sa.Float(), nullable=False),
        sa.Column("h", sa.Float(), nullable=False),
        sa.Column("l", sa.Float(), nullable=False),
        sa.Column("c", sa.Float(), nullable=False),
        sa.Column("v", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "interval", "ts", name="uq_candles_symbol_interval_ts"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "DEBUG",
                "INFO",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="event_level",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_ts"), "events", ["ts"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("t212_ticker", sa.String(length=32), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("tradable", sa.Boolean(), nullable=False),
        sa.Column("min_qty", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("allocation", sa.Float(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loop", sa.String(length=16), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=True),
        sa.Column("signal", sa.String(length=16), nullable=True),
        sa.Column("action_taken", sa.String(length=32), nullable=False),
        sa.Column("deny_reason", sa.String(length=64), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decisions_ts"), "decisions", ["ts"], unique=False)
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("equity", sa.Float(), nullable=False),
        sa.Column("cash", sa.Float(), nullable=False),
        sa.Column("open_exposure", sa.Float(), nullable=False),
        sa.Column("drawdown", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equity_snapshots_ts"), "equity_snapshots", ["ts"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_ref", sa.String(length=64), nullable=False),
        sa.Column("t212_order_id", sa.String(length=64), nullable=True),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column(
            "side", sa.Enum("BUY", "SELL", name="order_side", native_enum=False), nullable=False
        ),
        sa.Column("qty", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "type",
            sa.Enum("MARKET", "STOP", "LIMIT", name="order_type", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_SUBMIT",
                "SUBMITTED",
                "FILLED",
                "PARTIALLY_FILLED",
                "CANCELLED",
                "REJECTED",
                "FAILED",
                name="order_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fill_price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_ref"),
    )
    op.create_index(op.f("ix_orders_t212_order_id"), "orders", ["t212_order_id"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("avg_entry", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("stop_price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "stop_mode",
            sa.Enum("broker", "bot", name="stop_mode", native_enum=False),
            nullable=True,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", name="position_status", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_index(op.f("ix_orders_t212_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_equity_snapshots_ts"), table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    op.drop_index(op.f("ix_decisions_ts"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_table("strategies")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_events_ts"), table_name="events")
    op.drop_table("events")
    op.drop_table("candles")
    op.drop_table("bot_state")
    # ### end Alembic commands ###
